CREATE TABLE ratios_de_payaso2
(
    departamento          TEXT,
    r_pnp_perulibre       TEXT,
    r_pnp_fp              TEXT,
    r_fa_perulibre        TEXT,
    r_fa_fp               TEXT,
    r_morado_perulibre    TEXT,
    r_morado_fp           TEXT,
    r_pps_perulibre       TEXT,
    r_pps_fp              TEXT,
    r_vn_perulibre        TEXT,
    r_vn_fp               TEXT,
    r_ap_perulibre        TEXT,
    r_ap_fp               TEXT,
    r_avpais_perulibre    TEXT,
    r_avpais_fp           TEXT,
    r_pp_perulibre        TEXT,
    r_pp_fp               TEXT,
    r_jpp_perulibre       TEXT,
    r_jpp_fp              TEXT,
    r_ppc_perulibre       TEXT,
    r_ppc_fp              TEXT,
    r_fp_perulibre        TEXT,
    r_fp_fp               TEXT,
    r_upp_perulibre       TEXT,
    r_upp_fp              TEXT,
    r_rp_perulibre        TEXT,
    r_rp_fp               TEXT,
    r_runa_perulibre      TEXT,
    r_runa_fp             TEXT,
    r_sp_perulibre        TEXT,
    r_sp_fp               TEXT,
    r_perulibre_perulibre TEXT,
    r_perulibre_fp        TEXT,
    r_dd_perulibre        TEXT,
    r_dd_fp               TEXT,
    r_app_perulibre       TEXT,
    r_app_fp              TEXT
);

