create table payasada_csm
(
    mesa TEXT,
    v2_CCODI_UBIGEO TEXT,
    v2_DEPARTAMENTO TEXT,
    v2_PROVINCIA TEXT,
    v2_DISTRITO TEXT,
    v2_perulibre NUM,
    v2_fp NUM,
    v2_blanco NUM,
    v2_nulos NUM,
    v2_OBSERVACION TEXT,
    v2_OBSERVACION_TXT TEXT,
    mm_perulibre,
    mm_fp,
    cumplimiento_mm_perulibre,
    cumplimiento_mm_fp,
    esc1_perulibre,
    esc1_fp,
    cumplimiento_esc1_perulibre,
    cumplimiento_esc1_fp,
    esc2_perulibre,
    esc2_fp,
    cumplimiento_esc2_perulibre,
    cumplimiento_esc2_fp,
    delta_perulibre,
    delta_fp,
    esc3_prob_perulibre,
    esc3_prob_fp,
    esc3_desc_perulibre,
    esc3_desc_fp,
    alerta_por_nulos_y_blancos,
    acta_falsa_perulibre,
    acta_falsa_fp,
    anulada,
    hallazgo_perulibre,
    sospechoso_perulibre,
    hallazgo_fp,
    sospechoso_fp,
    PRIMARY KEY (mesa),
    FOREIGN KEY(mesa) REFERENCES mesas_20210411(mesa),
    FOREIGN KEY(mesa) REFERENCES mesas_20210606(mesa)
);
